const baseConfig = require("@unisalon/config/tailwind");

/** @type {import('tailwindcss').Config} */
module.exports = {
  ...baseConfig,
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    ...baseConfig.theme,
    extend: {
      ...baseConfig.theme?.extend,
      colors: {
        ...baseConfig.theme?.extend?.colors,
        "on-background": "#02060C",
        "surface-container-highest": "#e5e2e2",
        "surface-container-high": "#eae7e8",
        "surface-container-low": "#f6f3f3",
        "secondary-fixed-dim": "#e9c349",
        "on-primary-fixed-variant": "#41474f",
        "error": "#ba1a1a",
        "outline": "#75777b",
        "tertiary-fixed-dim": "#dbc1b4",
        "surface-dim": "#dcd9da",
        "inverse-on-surface": "#f3f0f0",
        "on-secondary-container": "#745c00",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "secondary-container": "#fed65b",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#261810",
        "surface-tint": "#585f67",
        "on-error": "#ffffff",
        "on-surface-variant": "#44474b",
        "primary": "#02060C",
        "tertiary-fixed": "#f8ddcf",
        "surface": "#fcf8f9",
        "on-secondary-fixed-variant": "#574500",
        "surface-variant": "#e5e2e2",
        "inverse-primary": "#c1c7d1",
        "surface-container": "#f0eded",
        "surface-bright": "#fcf8f9",
        "tertiary-container": "#261810",
        "on-secondary-fixed": "#241a00",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#161c23",
        "on-tertiary-fixed-variant": "#554339",
        "tertiary": "#000000",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#957f73",
        "primary-fixed": "#dde3ed",
        "inverse-surface": "#313031",
        "secondary-fixed": "#ffe088",
        "primary-container": "#161c23",
        "secondary": "#735c00",
        "on-primary-container": "#7e848d",
        "on-surface": "#1b1b1c",
        "outline-variant": "#c5c6cb",
        "background": "#fcf8f9",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#c1c7d1",
        
        "rating-green": "#1C893B",
        "text-primary": "#02060C",
        "text-secondary": "#686B78",
        "border-light": "#F0F0F0",
        "offer-bg": "#E9F8EC",
        "offer-text": "#1C893B",

        // App-specific semantic overrides mapped to monochromatic palette
        "brand-gold": "#ffe088",
        "brand-slate": "#02060C",
        "brand-teal": "#735c00",
        
        // Custom surface mappings to match Stitch
        "surface-card": "#ffffff",
        "surface-border": "#F0F0F0",
      },
      borderRadius: {
        ...baseConfig.theme?.extend?.borderRadius,
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        ...baseConfig.theme?.extend?.spacing,
        "gutter": "16px",
        "stack-lg": "40px",
        "stack-md": "20px",
        "margin-desktop": "40px",
        "stack-sm": "8px",
        "base": "8px",
        "margin-mobile": "16px",
        "container-max": "1440px",
        "card-gap": "20px",
        "container-padding": "24px",
        "section-margin": "40px",
      },
      fontFamily: {
        sans: ["Be Vietnam Pro", "sans-serif"],
        display: ["Metrophobic", "sans-serif"],
      }
    }
  }
};
